/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonacoEditorIndexRouteImport } from './routes/monaco-editor/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonacoEditorIndexRoute = MonacoEditorIndexRouteImport.update({
  id: '/monaco-editor/',
  path: '/monaco-editor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/monaco-editor': typeof MonacoEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/monaco-editor': typeof MonacoEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/monaco-editor/': typeof MonacoEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/monaco-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/monaco-editor'
  id: '__root__' | '/' | '/monaco-editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MonacoEditorIndexRoute: typeof MonacoEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monaco-editor/': {
      id: '/monaco-editor/'
      path: '/monaco-editor'
      fullPath: '/monaco-editor'
      preLoaderRoute: typeof MonacoEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MonacoEditorIndexRoute: MonacoEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
